spring.application.name=formBackend
# Supabase PostgreSQL Bağlantı Ayarları
#spring.datasource.url=jdbc:postgresql://db.ifdvsfhfbfdfyqhczjae.supabase.co:5432/postgres?user=postgres&password=123321mM*123gg
#spring.datasource.username=postgres
#spring.datasource.password=123321mM*123gg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# JPA ve Hibernate Ayarları
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Tabloları SQL ile biz oluşturduğumuz için update veya validate kullanıyoruz
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=SebaYanginSondurmeSistemleriGuvende2026SebaYanginSondurmeSistemleriGuvende2026

server.port=${PORT:8080}